#pragma checksum "..\..\..\MainWindow.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "821AA6975E0FC4C928E390682427EBBD"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Windows.Controls;
using Microsoft.Windows.Controls.Primitives;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using Timelapse_Template_Editor;


namespace Timelapse_Template_Editor {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 6 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Timelapse_Template_Editor.MainWindow OnlyWindow;
        
        #line default
        #line hidden
        
        
        #line 150 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel mainUI;
        
        #line default
        #line hidden
        
        
        #line 153 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem NewFileMenuItem;
        
        #line default
        #line hidden
        
        
        #line 158 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem OpenFileMenuItem;
        
        #line default
        #line hidden
        
        
        #line 163 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem ConvertFileMenuItem;
        
        #line default
        #line hidden
        
        
        #line 175 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem ExitFileMenuItem;
        
        #line default
        #line hidden
        
        
        #line 182 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem AboutMenuItem;
        
        #line default
        #line hidden
        
        
        #line 188 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition DisplayGrid;
        
        #line default
        #line hidden
        
        
        #line 189 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition EditButton;
        
        #line default
        #line hidden
        
        
        #line 192 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RowDefinition EditScheme;
        
        #line default
        #line hidden
        
        
        #line 193 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RowDefinition MenuPreview;
        
        #line default
        #line hidden
        
        
        #line 197 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Microsoft.Windows.Controls.DataGrid TemplateDataGrid;
        
        #line default
        #line hidden
        
        
        #line 359 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button MoveRowUpButton;
        
        #line default
        #line hidden
        
        
        #line 360 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button MoveRowDownButton;
        
        #line default
        #line hidden
        
        
        #line 365 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddCountRowButton;
        
        #line default
        #line hidden
        
        
        #line 366 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddChoiceRowButton;
        
        #line default
        #line hidden
        
        
        #line 367 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddNoteRowButton;
        
        #line default
        #line hidden
        
        
        #line 371 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RemoveRowButton;
        
        #line default
        #line hidden
        
        
        #line 384 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.WrapPanel wp;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Timelapse Template Editor;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.OnlyWindow = ((Timelapse_Template_Editor.MainWindow)(target));
            return;
            case 2:
            
            #line 122 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.MoveMenuItem_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 127 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.MoveMenuItem_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 132 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.EditMenuItem_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            
            #line 137 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.DeleteMenuItem_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.mainUI = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 7:
            this.NewFileMenuItem = ((System.Windows.Controls.MenuItem)(target));
            
            #line 153 "..\..\..\MainWindow.xaml"
            this.NewFileMenuItem.Click += new System.Windows.RoutedEventHandler(this.NewFileMenuItem_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.OpenFileMenuItem = ((System.Windows.Controls.MenuItem)(target));
            
            #line 158 "..\..\..\MainWindow.xaml"
            this.OpenFileMenuItem.Click += new System.Windows.RoutedEventHandler(this.OpenFileMenuItem_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.ConvertFileMenuItem = ((System.Windows.Controls.MenuItem)(target));
            
            #line 163 "..\..\..\MainWindow.xaml"
            this.ConvertFileMenuItem.Click += new System.Windows.RoutedEventHandler(this.ConvertCodeTemplateFileMenuItem_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.ExitFileMenuItem = ((System.Windows.Controls.MenuItem)(target));
            
            #line 175 "..\..\..\MainWindow.xaml"
            this.ExitFileMenuItem.Click += new System.Windows.RoutedEventHandler(this.ExitFileMenuItem_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.AboutMenuItem = ((System.Windows.Controls.MenuItem)(target));
            
            #line 182 "..\..\..\MainWindow.xaml"
            this.AboutMenuItem.Click += new System.Windows.RoutedEventHandler(this.AboutMenuItem_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.DisplayGrid = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 13:
            this.EditButton = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 14:
            this.EditScheme = ((System.Windows.Controls.RowDefinition)(target));
            return;
            case 15:
            this.MenuPreview = ((System.Windows.Controls.RowDefinition)(target));
            return;
            case 16:
            this.TemplateDataGrid = ((Microsoft.Windows.Controls.DataGrid)(target));
            
            #line 197 "..\..\..\MainWindow.xaml"
            this.TemplateDataGrid.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.TemplateDataGrid_PreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 197 "..\..\..\MainWindow.xaml"
            this.TemplateDataGrid.BeginningEdit += new System.EventHandler<Microsoft.Windows.Controls.DataGridBeginningEditEventArgs>(this.TemplateDataGrid_BeginningEdit);
            
            #line default
            #line hidden
            
            #line 197 "..\..\..\MainWindow.xaml"
            this.TemplateDataGrid.LayoutUpdated += new System.EventHandler(this.TemplateDataGrid_LayoutUpdated);
            
            #line default
            #line hidden
            
            #line 197 "..\..\..\MainWindow.xaml"
            this.TemplateDataGrid.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.TemplateDataGrid_SelectionChanged);
            
            #line default
            #line hidden
            
            #line 197 "..\..\..\MainWindow.xaml"
            this.TemplateDataGrid.CurrentCellChanged += new System.EventHandler<System.EventArgs>(this.TemplateDataGrid_CurrentCellChanged);
            
            #line default
            #line hidden
            return;
            case 18:
            this.MoveRowUpButton = ((System.Windows.Controls.Button)(target));
            
            #line 359 "..\..\..\MainWindow.xaml"
            this.MoveRowUpButton.Click += new System.Windows.RoutedEventHandler(this.MoveRowButton_Click_Efficient);
            
            #line default
            #line hidden
            return;
            case 19:
            this.MoveRowDownButton = ((System.Windows.Controls.Button)(target));
            
            #line 360 "..\..\..\MainWindow.xaml"
            this.MoveRowDownButton.Click += new System.Windows.RoutedEventHandler(this.MoveRowButton_Click_Efficient);
            
            #line default
            #line hidden
            return;
            case 20:
            this.AddCountRowButton = ((System.Windows.Controls.Button)(target));
            
            #line 365 "..\..\..\MainWindow.xaml"
            this.AddCountRowButton.Click += new System.Windows.RoutedEventHandler(this.AddRowButton_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.AddChoiceRowButton = ((System.Windows.Controls.Button)(target));
            
            #line 366 "..\..\..\MainWindow.xaml"
            this.AddChoiceRowButton.Click += new System.Windows.RoutedEventHandler(this.AddRowButton_Click);
            
            #line default
            #line hidden
            return;
            case 22:
            this.AddNoteRowButton = ((System.Windows.Controls.Button)(target));
            
            #line 367 "..\..\..\MainWindow.xaml"
            this.AddNoteRowButton.Click += new System.Windows.RoutedEventHandler(this.AddRowButton_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            this.RemoveRowButton = ((System.Windows.Controls.Button)(target));
            
            #line 371 "..\..\..\MainWindow.xaml"
            this.RemoveRowButton.Click += new System.Windows.RoutedEventHandler(this.RemoveRowButton_Click);
            
            #line default
            #line hidden
            return;
            case 24:
            this.wp = ((System.Windows.Controls.WrapPanel)(target));
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 17:
            
            #line 308 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.ComboBox)(target)).SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ComboBox_SelectionChanged);
            
            #line default
            #line hidden
            
            #line 308 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.ComboBox)(target)).KeyDown += new System.Windows.Input.KeyEventHandler(this.ComboBox_KeyDown);
            
            #line default
            #line hidden
            
            #line 308 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.ComboBox)(target)).IsKeyboardFocusWithinChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.comboBox_IsKeyboardFocusWithinChanged);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

